//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchPrintYay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchPrintYay.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always colored.
        /// </summary>
        internal static string DefaultAlwaysColoredParamname {
            get {
                return ResourceManager.GetString("DefaultAlwaysColoredParamname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Number&gt;_&lt;Sheet Number&gt;.dwg.
        /// </summary>
        internal static string DefaultDwgName {
            get {
                return ResourceManager.GetString("DefaultDwgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Sheet Number&gt;_&lt;Sheet Name&gt;.pdf.
        /// </summary>
        internal static string DefaultPDFfilename {
            get {
                return ResourceManager.GetString("DefaultPDFfilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename is too long.
        /// </summary>
        internal static string ExceptionFilenameTooLong {
            get {
                return ResourceManager.GetString("ExceptionFilenameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the titleblock with elements outside the sheet edge or refresh the family..
        /// </summary>
        internal static string MessageCheckTitleblockSize {
            get {
                return ResourceManager.GetString("MessageCheckTitleblockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Default format has been set..
        /// </summary>
        internal static string MessageDefaultSheetFormatSet {
            get {
                return ResourceManager.GetString("MessageDefaultSheetFormatSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nDefault format has been set. Try to launch print again. \nInfo about error:.
        /// </summary>
        internal static string MessageDefaultSizeAndStartAgain {
            get {
                return ResourceManager.GetString("MessageDefaultSizeAndStartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  dwg export profile isnt found .
        /// </summary>
        internal static string MessageDwgNotFound {
            get {
                return ResourceManager.GetString("MessageDwgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error info:.
        /// </summary>
        internal static string MessageErrorText {
            get {
                return ResourceManager.GetString("MessageErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print has been finished!.
        /// </summary>
        internal static string MessageFinishPrintTItle {
            get {
                return ResourceManager.GetString("MessageFinishPrintTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In file .
        /// </summary>
        internal static string MessageInFile {
            get {
                return ResourceManager.GetString("MessageInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Maybe you dont have administrator permissions. .
        /// </summary>
        internal static string MessageNoAdmin {
            get {
                return ResourceManager.GetString("MessageNoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonstandard sheet format is found. Try to launch print again. Sheet:.
        /// </summary>
        internal static string MessageNonStandardList {
            get {
                return ResourceManager.GetString("MessageNonStandardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet arent selected. Please select sheets in Project Browser using Shift or Ctrl in advance..
        /// </summary>
        internal static string MessageNoSelectedSheets {
            get {
                return ResourceManager.GetString("MessageNoSelectedSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No titleblocks on sheet: .
        /// </summary>
        internal static string MessageNoTitleblockOnSheet {
            get {
                return ResourceManager.GetString("MessageNoTitleblockOnSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Instance parameter exists:.
        /// </summary>
        internal static string MessageParameterExists {
            get {
                return ResourceManager.GetString("MessageParameterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF merge and ColorExceptions are supperted only with PDFCreator. This features will be disabled..
        /// </summary>
        internal static string MessagePrinterNotPdfCreator {
            get {
                return ResourceManager.GetString("MessagePrinterNotPdfCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF print takes a lot of time or maybe a failure was happened. Please waint until the end of print..
        /// </summary>
        internal static string MessagePrintTooMuchTime {
            get {
                return ResourceManager.GetString("MessagePrintTooMuchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to set registy key:.
        /// </summary>
        internal static string MessageRegistryKeyName {
            get {
                return ResourceManager.GetString("MessageRegistryKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , value:.
        /// </summary>
        internal static string MessageRegistryKeyValue {
            get {
                return ResourceManager.GetString("MessageRegistryKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet size isnt found for sheet: .
        /// </summary>
        internal static string MessageSheetFormatNotFound {
            get {
                return ResourceManager.GetString("MessageSheetFormatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with sheet size! Width or height isn&apos;t match for more than .
        /// </summary>
        internal static string MessageSheetSizeProblem {
            get {
                return ResourceManager.GetString("MessageSheetSizeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets are printed:.
        /// </summary>
        internal static string MessageSheetsPrinted {
            get {
                return ResourceManager.GetString("MessageSheetsPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply Revit sheet format. Try to launch print again. Sheet: .
        /// </summary>
        internal static string MessageUnableToApplyRevitSheetFormat {
            get {
                return ResourceManager.GetString("MessageUnableToApplyRevitSheetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create format: .
        /// </summary>
        internal static string MessageUnableToCreateSheetFormat {
            get {
                return ResourceManager.GetString("MessageUnableToCreateSheetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get saved print settings,reset to default settings.
        /// </summary>
        internal static string MessageUnableToGetSavedPrintSettings {
            get {
                return ResourceManager.GetString("MessageUnableToGetSavedPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine titleblock sizes.\n.
        /// </summary>
        internal static string MessageUnableToGetTitleblockSize {
            get {
                return ResourceManager.GetString("MessageUnableToGetTitleblockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to tune PDFCreator, default settings will be applied. Please tune PDFCreator manually..
        /// </summary>
        internal static string MessageUnableToMakePdfSettings {
            get {
                return ResourceManager.GetString("MessageUnableToMakePdfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to tune PDFCreator! It its your first launch - try to print any other document with PDFCreator. Then launch plugin again..
        /// </summary>
        internal static string MessageUnableToMakePdfSettingsFirstLaunch {
            get {
                return ResourceManager.GetString("MessageUnableToMakePdfSettingsFirstLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reset PDFCreator settings. Please try to reinstall PDFCreator..
        /// </summary>
        internal static string MessageUnableToRestorePdfSettings {
            get {
                return ResourceManager.GetString("MessageUnableToRestorePdfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save files in this folder, select another folder:.
        /// </summary>
        internal static string MessageUnableToSaveFiles {
            get {
                return ResourceManager.GetString("MessageUnableToSaveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set sheet size.
        /// </summary>
        internal static string MessageUnableToSetSheetSize {
            get {
                return ResourceManager.GetString("MessageUnableToSetSheetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Width.
        /// </summary>
        internal static string ParameterBultinSheetHeight {
            get {
                return ResourceManager.GetString("ParameterBultinSheetHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Height.
        /// </summary>
        internal static string ParameterBultinSheetWidth {
            get {
                return ResourceManager.GetString("ParameterBultinSheetWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print profiles.
        /// </summary>
        internal static string TransactionPrintProfiles {
            get {
                return ResourceManager.GetString("TransactionPrintProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh schedules.
        /// </summary>
        internal static string TransactionSchedulesRefresh {
            get {
                return ResourceManager.GetString("TransactionSchedulesRefresh", resourceCulture);
            }
        }
    }
}
